version: 2.0
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  nodefetch1:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install node-fetch@1
      - run: ./node_modules/.bin/mocha test/server.js
  nodefetch2:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install node-fetch@2
      - run: ./node_modules/.bin/mocha test/server.js

workflows:
  version: 2
  checkout_and_test:
    jobs:
      - checkout_code
      - nodefetch1:
          requires:
            - checkout_code
      - nodefetch2:
          requires:
            - checkout_code
