version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
  nodefetch1:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - npm install node-fetch@1
      - mocha
# workflows:
#   version: 2
#   test:
#     jobs:
#       requires:
#         - nodefetch1
