version: 2.0

references:
  triggerable-by-tag: &triggerable-by-tag
    # For a tag push unaffected by any filters, CircleCI skips the job
    # https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
    filters:
      tags:
        only: /.*/
  run-after-first-jobs: &run-after-first-jobs
    requires:
      - test
      - lint
      - build

  nodelts: &nodelts
    docker:
      - image: cimg/node:lts
  # browsers: &browsers
  #   docker:
  #     - image: circleci/node:12.18.3-browsers
  nodecurrent: &nodecurrent
    docker:
      - image: cimg/node:current

  workspace: &workspace
    attach_workspace:
      at: ~/project
  persist: &persist
    persist_to_workspace:
      root: .
      paths:
        - .

jobs:
  checkout_code:
    <<: *nodelts
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run: if [ ! -d "node_modules" ]; then npm install --no-package-lock; fi
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - *persist

  build:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm run build
      - *persist
  lint:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm run lint:ci
      - run: npm run prettier:ci

  typelint:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm run types:lint
      - run: npm run types:check --noEmit=true

  test:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm run test:ci

  nodefetch3:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm install node-fetch@3
      - run: TESTING_ENV=node-fetch npm run test:legacy

  commonjs:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm run build
      - run: TESTING_ENV=commonjs npm run test:legacy
  jest:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm run build
      - run: npm run test:jest
  # chrome:
  #   <<: *browsers
  #   steps:
  #     - *workspace
  #     - run: TEST_BROWSER=Chrome make test-browser

  # firefox:
  #   <<: *browsers
  #   steps:
  #     - *workspace
  #     - run: npm install karma-firefox-launcher
  #     - run: TEST_BROWSER=Firefox make test-browser

  publish:
    <<: *nodelts
    steps:
      - *workspace
      - run: npm run build
      - run:
          name: NPM auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: NPM publish
          command: ./scripts/circleci-npm-publish.sh

workflows:
  version: 2
  fetch-mock-ci-cd:
    jobs:
      - checkout_code: *triggerable-by-tag
      - test:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      - lint:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      - build:
          <<: *triggerable-by-tag
          requires:
            - checkout_code
      # could be parallel with build, lint, and unit but it's a slow job
      # And circlecifree tier only has 3 concurrent jobs, so overall faster
      # to defer
      - typelint:
          <<: *triggerable-by-tag
          <<: *run-after-first-jobs
      - nodefetch3:
          <<: *triggerable-by-tag
          <<: *run-after-first-jobs
      - commonjs:
          <<: *triggerable-by-tag
          <<: *run-after-first-jobs
      - jest:
          <<: *triggerable-by-tag
          <<: *run-after-first-jobs
      # - chrome:
      #     <<: *triggerable-by-tag
      #     <<: *run-after-first-jobs
      # - firefox:
      #     <<: *triggerable-by-tag
      #     <<: *run-after-first-jobs
      - publish:
          requires:
            - nodefetch3
            # - chrome
            # - firefox
            - build
            - typelint
            - commonjs
            - jest
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[\w-]+-v?\d+\.\d+\.\d+(?:-(beta|alpha)\.\d+)?$/
